[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "vol-surface"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = ["pandas", "numpy", "matplotlib", "requests", "scipy"]

[project.optional-dependencies]
dev = ["ipykernel"]

[tool.hatch.build.targets.wheel]
packages = ["engine"]
